version: '3.5'
services:

  neo4j: 
    image: neo4j:3.5
    volumes: 
      - ./neo4j/data:/data
    ports:
      - 7474:7474 # admin interface
      - 7687:7687 # bolt
    # For development only!
    environment:
      NEO4J_AUTH: none

  twitter:
    build: ./data_collection
    volumes:
      - ./data_collection:/usr/local/src/data_collection
    command: python runner.py twitter
    restart: on-failure
    depends_on:
      - neo4j
    environment:
      NEO4J_URI: bolt://neo4j:7687

  newsapi:
    build: ./data_collection
    volumes:
      - ./data_collection:/usr/local/src/data_collection
    command: python runner.py newsapi -t 600
    restart: on-failure
    links:
      - neo4j
    environment:
      NEO4J_URI: bolt://neo4j:7687

  corenlp:
    image: frnkenstien/corenlp
    ports:
      - 9000:9000

  mariadb:
    image: mariadb
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: donotuseinproduction
    volumes:
      - ./data_database/data:/var/lib/mysql
      - ./data_database/create_database.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data_database/conf:/etc/mysql/conf.d
    restart: on-failure
    network_mode: "host"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
        - PMA_ARBITRARY=1
        - PMA_HOST=mariadb
    restart: always
    ports:
        - 8080:80
    depends_on:
        - mariadb
    network_mode: "host"

  cluster_evaluation:
    build: ./data_processing
    volumes:
      - ./data_processing:/usr/local/src/data_processing
    depends_on:
      - mariadb
    restart: on-failure
    network_mode: "host"