version: '3'
services:

  neo4j: 
    image: neo4j:3.5
    volumes: 
      - ./neo4j/data:/data
    ports:
      - 7474:7474
      - 7687:7687
    # For development only!
    environment:
      NEO4J_AUTH: none 
