version: '3'
services:

  neo4j: 
    image: neo4j:3.5
    volumes: 
      - ./neo4j/data:/data
    ports:
      - 7474:7474 # admin interface
      - 7687:7687 # bolt
    # For development only!
    environment:
      NEO4J_AUTH: none

  twitter:
    build: ./src
    volumes:
      - ./src:/usr/local/src/app
    command: python runner.py twitter 60
    restart: on-failure
    links:
      - neo4j
